// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Data.Migrations
{
    [DbContext(typeof(PlantMonitorDbContext))]
    [Migration("20260714151118_M4_LineConfigPersistence")]
    partial class M4_LineConfigPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("backend.Models.Plc.LineProtocolAssignmentEntity", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlcIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("PollIntervalMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PresetName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresetVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("LineId");

                    b.ToTable("line_protocol_assignments", (string)null);
                });

            modelBuilder.Entity("backend.Models.Plc.LineTagCatalogEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogicalKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlcAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadFrequencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Scale")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LineId", "LogicalKey")
                        .IsUnique();

                    b.HasIndex("LineId", "PlcAddress")
                        .IsUnique();

                    b.ToTable("line_tag_catalog_entries", (string)null);
                });

            modelBuilder.Entity("backend.Models.Plc.LineTagOverrideEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlcAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Scale")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LineId", "TagKey")
                        .IsUnique();

                    b.ToTable("line_tag_overrides", (string)null);
                });

            modelBuilder.Entity("backend.Models.Plc.PlcProtocolPresetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PresetName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresetVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Manufacturer", "PresetName", "PresetVersion")
                        .IsUnique();

                    b.ToTable("plc_protocol_presets", (string)null);
                });

            modelBuilder.Entity("backend.Models.Plc.PlcProtocolPresetTagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlcAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Scale")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresetId", "TagKey")
                        .IsUnique();

                    b.ToTable("plc_protocol_preset_tags", (string)null);
                });

            modelBuilder.Entity("backend.Models.Production.CompletedProductionRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AutoPercentage")
                        .HasColumnType("REAL");

                    b.Property<double>("AutoTimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("LineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("ManualPercentage")
                        .HasColumnType("REAL");

                    b.Property<double>("ManualTimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlcIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductionLength")
                        .HasColumnType("REAL");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("RuntimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndTimeUtc");

                    b.HasIndex("LineId");

                    b.ToTable("completed_production_runs", (string)null);
                });

            modelBuilder.Entity("backend.Models.Production.CompletedProductionRunZoneStatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageAbsoluteDeviation")
                        .HasColumnType("REAL");

                    b.Property<double>("CurrentDeviation")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxNegativeDeviation")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxPositiveDeviation")
                        .HasColumnType("REAL");

                    b.Property<long>("MeasurementCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<double>("RunningAbsoluteDeviationSum")
                        .HasColumnType("REAL");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Zone", "Segment")
                        .IsUnique();

                    b.ToTable("completed_production_run_zone_stats", (string)null);
                });

            modelBuilder.Entity("backend.Models.Production.RecipeToleranceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeasurementType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToleranceMinus")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TolerancePlus")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "MeasurementType", "Version")
                        .IsUnique();

                    b.ToTable("recipe_tolerances", (string)null);
                });

            modelBuilder.Entity("backend.Models.Plc.LineTagOverrideEntity", b =>
                {
                    b.HasOne("backend.Models.Plc.LineProtocolAssignmentEntity", "Assignment")
                        .WithMany("TagOverrides")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("backend.Models.Plc.PlcProtocolPresetTagEntity", b =>
                {
                    b.HasOne("backend.Models.Plc.PlcProtocolPresetEntity", "Preset")
                        .WithMany("Tags")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("backend.Models.Production.CompletedProductionRunZoneStatEntity", b =>
                {
                    b.HasOne("backend.Models.Production.CompletedProductionRunEntity", "Run")
                        .WithMany("ZoneStats")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("backend.Models.Plc.LineProtocolAssignmentEntity", b =>
                {
                    b.Navigation("TagOverrides");
                });

            modelBuilder.Entity("backend.Models.Plc.PlcProtocolPresetEntity", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("backend.Models.Production.CompletedProductionRunEntity", b =>
                {
                    b.Navigation("ZoneStats");
                });
#pragma warning restore 612, 618
        }
    }
}
